# BUTTERFLY Common OpenAPI Schemas
# Version: 1.0.0
# 
# This file contains reusable schema definitions for all BUTTERFLY
# ecosystem services. Import these schemas using $ref to ensure
# consistency across all service APIs.
#
# Usage in service OpenAPI specs:
#   components:
#     schemas:
#       ProblemDetail:
#         $ref: 'https://raw.githubusercontent.com/254carbon/butterfly-common/main/src/main/resources/openapi/common-schemas.yaml#/components/schemas/ProblemDetail'

openapi: '3.1.0'
info:
  title: BUTTERFLY Common Schemas
  description: Reusable schema definitions for BUTTERFLY ecosystem APIs
  version: '1.0.0'
  contact:
    name: 254STUDIOZ Engineering
    email: engineering@254studioz.com

components:
  schemas:
    # =========================================
    # Error Response (RFC 7807 Problem Details)
    # =========================================
    
    ProblemDetail:
      type: object
      description: |
        RFC 7807 Problem Details response format with BUTTERFLY extensions.
        All error responses from BUTTERFLY services follow this format.
      required:
        - type
        - title
        - status
      properties:
        type:
          type: string
          format: uri
          description: URI reference identifying the problem type
          example: 'https://api.butterfly.254studioz.com/errors/not-found'
        title:
          type: string
          description: Short, human-readable summary of the problem type
          example: 'Resource Not Found'
        status:
          type: integer
          format: int32
          description: HTTP status code
          minimum: 100
          maximum: 599
          example: 404
        detail:
          type: string
          description: Human-readable explanation specific to this occurrence
          example: 'Capsule with ID ''abc-123'' was not found'
        instance:
          type: string
          format: uri
          description: URI reference identifying the specific occurrence
          example: '/api/v1/capsules/abc-123'
        traceId:
          type: string
          description: Distributed tracing correlation ID
          example: 'trace-456def'
        timestamp:
          type: string
          format: date-time
          description: ISO 8601 timestamp of error occurrence
          example: '2025-01-15T10:30:00Z'
        service:
          type: string
          description: Originating service identifier
          example: 'capsule'
        errorCode:
          type: string
          description: Machine-readable error code for client handling
          example: 'NOT_FOUND'
        extensions:
          type: object
          description: Additional error-specific properties
          additionalProperties: true
          example:
            fieldErrors:
              name: 'Name is required'
              email: 'Invalid email format'
    
    # =========================================
    # Validation Error Response
    # =========================================
    
    ValidationError:
      allOf:
        - $ref: '#/components/schemas/ProblemDetail'
        - type: object
          properties:
            extensions:
              type: object
              properties:
                fieldErrors:
                  type: object
                  additionalProperties:
                    type: string
                  description: Map of field names to error messages
                  example:
                    name: 'Name is required'
                    email: 'Invalid email format'

    # =========================================
    # Standard API Response Wrapper
    # =========================================
    
    ApiResponse:
      type: object
      description: Standard wrapper for successful API responses
      required:
        - data
      properties:
        data:
          description: Response payload (type varies by endpoint)
        meta:
          $ref: '#/components/schemas/ResponseMeta'
        pagination:
          $ref: '#/components/schemas/Pagination'
        warnings:
          type: array
          items:
            $ref: '#/components/schemas/Warning'
          description: Non-fatal warnings
        links:
          type: object
          additionalProperties:
            type: string
          description: HATEOAS-style navigation links
    
    ResponseMeta:
      type: object
      description: Response metadata
      properties:
        timestamp:
          type: string
          format: date-time
          description: Response generation timestamp
        service:
          type: string
          description: Responding service identifier
        requestId:
          type: string
          description: Unique request identifier
    
    # =========================================
    # Pagination
    # =========================================
    
    Pagination:
      type: object
      description: Pagination information for list responses
      properties:
        offset:
          type: integer
          format: int32
          description: Number of items skipped
          minimum: 0
          example: 0
        limit:
          type: integer
          format: int32
          description: Maximum items per page
          minimum: 1
          maximum: 1000
          example: 20
        total:
          type: integer
          format: int64
          description: Total number of items
          minimum: 0
          example: 150
        page:
          type: integer
          format: int32
          description: Current page number (0-indexed)
          minimum: 0
          example: 0
        totalPages:
          type: integer
          format: int32
          description: Total number of pages
          minimum: 0
          example: 8
        hasPrevious:
          type: boolean
          description: Whether a previous page exists
          example: false
        hasNext:
          type: boolean
          description: Whether a next page exists
          example: true
        resource:
          type: string
          description: Resource type name
          example: 'capsules'
    
    # =========================================
    # Warning
    # =========================================
    
    Warning:
      type: object
      description: Non-fatal warning message
      required:
        - code
        - message
      properties:
        code:
          type: string
          description: Warning code
          example: 'DEPRECATED_FIELD'
        message:
          type: string
          description: Human-readable warning message
          example: 'Field ''oldName'' is deprecated, use ''newName'' instead'
        field:
          type: string
          description: Related field name, if applicable
          example: 'oldName'
    
    # =========================================
    # Health Check Response
    # =========================================
    
    HealthStatus:
      type: object
      description: Service health check response
      required:
        - status
      properties:
        status:
          type: string
          enum: [UP, DOWN, DEGRADED, UNKNOWN]
          description: Overall health status
          example: 'UP'
        serviceId:
          type: string
          description: Service identifier
          example: 'capsule'
        version:
          type: string
          description: Service version
          example: '1.8.0'
        timestamp:
          type: string
          format: date-time
          description: Health check timestamp
        components:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/ComponentHealth'
          description: Health of individual components
    
    ComponentHealth:
      type: object
      description: Individual component health
      properties:
        status:
          type: string
          enum: [UP, DOWN, UNKNOWN]
        details:
          type: object
          additionalProperties: true
    
    # =========================================
    # Common DTOs
    # =========================================
    
    TimeRange:
      type: object
      description: Time range specification
      properties:
        from:
          type: string
          format: date-time
          description: Start time (inclusive)
        to:
          type: string
          format: date-time
          description: End time (exclusive)
    
    SortOrder:
      type: string
      enum: [ASC, DESC]
      description: Sort direction
      default: DESC
    
    # =========================================
    # Security Schemas
    # =========================================
    
    TenantInfo:
      type: object
      description: Tenant context information
      properties:
        tenantId:
          type: string
          description: Tenant identifier
          example: 'tenant-123'
        tenantName:
          type: string
          description: Human-readable tenant name
          example: 'Acme Corp'
        tier:
          type: string
          enum: [FREE, STARTER, PROFESSIONAL, ENTERPRISE]
          description: Tenant service tier

  # =========================================
  # Common Headers
  # =========================================
  
  headers:
    X-Tenant-ID:
      description: Tenant identifier for multi-tenant operations
      schema:
        type: string
      example: 'tenant-123'
    
    X-Correlation-ID:
      description: Request correlation ID for distributed tracing
      schema:
        type: string
      example: 'corr-456def'
    
    X-API-Version:
      description: API version in response
      schema:
        type: string
      example: '1.0.0'
    
    X-Request-ID:
      description: Unique request identifier
      schema:
        type: string
      example: 'req-789ghi'
    
    X-RateLimit-Limit:
      description: Rate limit maximum requests per window
      schema:
        type: integer
      example: 1000
    
    X-RateLimit-Remaining:
      description: Remaining requests in current window
      schema:
        type: integer
      example: 950
    
    X-RateLimit-Reset:
      description: Unix timestamp when rate limit resets
      schema:
        type: integer
      example: 1705312800
    
    Deprecation:
      description: RFC 8594 deprecation indicator
      schema:
        type: string
      example: 'true'
    
    Sunset:
      description: RFC 8594 sunset date for deprecated endpoints
      schema:
        type: string
        format: date
      example: '2025-06-01'

  # =========================================
  # Common Parameters
  # =========================================
  
  parameters:
    offsetParam:
      name: offset
      in: query
      description: Number of items to skip (for pagination)
      schema:
        type: integer
        format: int32
        minimum: 0
        default: 0
      example: 0
    
    limitParam:
      name: limit
      in: query
      description: Maximum number of items to return
      schema:
        type: integer
        format: int32
        minimum: 1
        maximum: 1000
        default: 20
      example: 20
    
    sortParam:
      name: sort
      in: query
      description: 'Sort field and direction (e.g., ''createdAt,desc'')'
      schema:
        type: string
      example: 'createdAt,desc'
    
    tenantIdHeader:
      name: X-Tenant-ID
      in: header
      description: Tenant identifier (optional if using JWT with tenant claim)
      schema:
        type: string
      example: 'tenant-123'
    
    correlationIdHeader:
      name: X-Correlation-ID
      in: header
      description: Correlation ID for request tracing
      schema:
        type: string
      example: 'corr-456def'

  # =========================================
  # Common Responses
  # =========================================
  
  responses:
    BadRequest:
      description: Bad request - validation error or malformed request
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ValidationError'
    
    Unauthorized:
      description: Authentication required
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
    
    Forbidden:
      description: Insufficient permissions
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
    
    NotFound:
      description: Resource not found
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
    
    RateLimited:
      description: Rate limit exceeded
      headers:
        Retry-After:
          description: Seconds to wait before retrying
          schema:
            type: integer
        X-RateLimit-Limit:
          $ref: '#/components/headers/X-RateLimit-Limit'
        X-RateLimit-Remaining:
          $ref: '#/components/headers/X-RateLimit-Remaining'
        X-RateLimit-Reset:
          $ref: '#/components/headers/X-RateLimit-Reset'
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
    
    InternalError:
      description: Internal server error
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'
    
    ServiceUnavailable:
      description: Service temporarily unavailable
      headers:
        Retry-After:
          description: Seconds to wait before retrying
          schema:
            type: integer
      content:
        application/problem+json:
          schema:
            $ref: '#/components/schemas/ProblemDetail'

  # =========================================
  # Security Schemes
  # =========================================
  
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT Bearer token authentication
    
    apiKey:
      type: apiKey
      in: header
      name: X-API-Key
      description: API key authentication
