package com.z254.butterfly.common.kafka;

/**
 * Centralized Kafka topic naming conventions for the BUTTERFLY ecosystem.
 * 
 * <p>All services should use these constants for topic names to ensure
 * consistency across the ecosystem.
 * 
 * <h2>Naming Convention</h2>
 * <ul>
 *   <li>Service events: {@code {service}.{domain}.{action}}</li>
 *   <li>Cross-service: {@code butterfly.{flow}.{stage}}</li>
 *   <li>DLQ: {@code {original-topic}.dlq}</li>
 *   <li>Internal: {@code {service}.internal.{purpose}}</li>
 * </ul>
 * 
 * <h2>Examples</h2>
 * <pre>{@code
 * // Publishing to CAPSULE events topic
 * kafkaTemplate.send(ButterflyTopics.CAPSULE_CREATED, event);
 * 
 * // Consuming from learning signals
 * @KafkaListener(topics = ButterflyTopics.LEARNING_SIGNALS)
 * public void handle(LearningSignal signal) { ... }
 * }</pre>
 * 
 * @since 1.0.0
 */
public final class ButterflyTopics {
    
    private ButterflyTopics() {
        // Utility class - no instantiation
    }
    
    // =========================================
    // PERCEPTION Topics
    // =========================================
    
    /**
     * Events detected by PERCEPTION intelligence.
     * Schema: PerceptionSignalEvent.avsc
     */
    public static final String PERCEPTION_EVENTS = "perception.events.detected";
    
    /**
     * Signals generated by PERCEPTION analysis.
     * Schema: PerceptionSignalEvent.avsc
     */
    public static final String PERCEPTION_SIGNALS = "perception.signals.generated";
    
    /**
     * Storylines created or updated by PERCEPTION.
     */
    public static final String PERCEPTION_STORYLINES = "perception.storylines.updated";
    
    /**
     * Trust score updates from PERCEPTION integrity module.
     */
    public static final String PERCEPTION_TRUST_SCORES = "perception.trust.scores";
    
    /**
     * Content ingestion events.
     */
    public static final String PERCEPTION_INGESTION = "perception.ingestion.events";
    
    /**
     * PERCEPTION to CAPSULE handoff events.
     * Schema: PerceptionToCapsuleEvent.avsc
     */
    public static final String PERCEPTION_TO_CAPSULE = "perception.capsule.handoff";
    
    // =========================================
    // PERCEPTION Model/Feature Lifecycle Topics
    // =========================================
    
    /**
     * Model lifecycle events from perception-models.
     * Includes: registration, stage transitions, drift alerts, evaluations.
     * Schema: ModelLifecycleEvent.avsc
     */
    public static final String PERCEPTION_MODEL_LIFECYCLE = "perception.models.lifecycle";
    
    /**
     * Model drift detection events from perception-models.
     * Published when drift exceeds configured thresholds.
     * Schema: ModelDriftEvent.avsc (existing in perception-models)
     */
    public static final String PERCEPTION_MODEL_DRIFT = "perception.models.drift";
    
    /**
     * Model quality metrics events.
     * Periodic metrics snapshots for PLATO ResearchOS integration.
     * Schema: ModelQualityMetrics.avsc
     */
    public static final String PERCEPTION_MODEL_METRICS = "perception.models.metrics";
    
    /**
     * Feature lifecycle events from perception-features.
     * Includes: version creation, drift detection, schema changes.
     * Schema: FeatureLifecycleEvent.avsc
     */
    public static final String PERCEPTION_FEATURE_LIFECYCLE = "perception.features.lifecycle";
    
    /**
     * Feature drift detection events.
     * Schema: FeatureDriftEvent.avsc
     */
    public static final String PERCEPTION_FEATURE_DRIFT = "perception.features.drift";
    
    // =========================================
    // CAPSULE Topics
    // =========================================
    
    /**
     * New capsule created events.
     */
    public static final String CAPSULE_CREATED = "capsule.events.created";
    
    /**
     * Capsule updated/revised events.
     */
    public static final String CAPSULE_UPDATED = "capsule.events.updated";
    
    /**
     * Capsule detection results.
     * Schema: CapsuleDetectionEvent.avsc
     */
    public static final String CAPSULE_DETECTION = "capsule.detection.events";
    
    /**
     * Capsule counterfactual validation results.
     */
    public static final String CAPSULE_COUNTERFACTUAL = "capsule.counterfactuals.validated";
    
    /**
     * Capsule embedding generation events.
     * Schema: embedding-batch.avsc
     */
    public static final String CAPSULE_EMBEDDINGS = "capsule.embeddings.generated";
    
    /**
     * Capsule tiering/archival events.
     * Schema: tiering-event.avsc
     */
    public static final String CAPSULE_TIERING = "capsule.tiering.events";
    
    // =========================================
    // ODYSSEY Topics
    // =========================================
    
    /**
     * Path weight updates from ODYSSEY.
     */
    public static final String ODYSSEY_PATHS = "odyssey.paths.updated";
    
    /**
     * Actor model updates from ODYSSEY.
     */
    public static final String ODYSSEY_ACTORS = "odyssey.actors.updated";
    
    /**
     * World state snapshot events.
     */
    public static final String ODYSSEY_WORLD_STATE = "odyssey.world.state";
    
    /**
     * Strategy synthesis results.
     * Schema: strategy-proposal.avsc
     */
    public static final String ODYSSEY_STRATEGY = "odyssey.strategy.proposals";
    
    /**
     * Gameboard intervention events.
     * Schema: GameboardIntervention.avsc
     */
    public static final String ODYSSEY_INTERVENTIONS = "odyssey.gameboard.interventions";
    
    /**
     * School consensus divergence alerts.
     */
    public static final String ODYSSEY_DIVERGENCE = "odyssey.schools.divergence";
    
    /**
     * Experiment outcome events.
     */
    public static final String ODYSSEY_EXPERIMENTS = "odyssey.experiments.outcomes";
    
    /**
     * Strategy outcome events with full attribution.
     * Includes: outcome status, P&L impact, model/feature/spec attribution.
     * Schema: StrategyOutcomeAttribution.avsc
     */
    public static final String ODYSSEY_STRATEGY_OUTCOMES = "odyssey.strategy.outcomes";
    
    // =========================================
    // NEXUS Topics
    // =========================================
    
    /**
     * Strategic synthesis completed events.
     * Schema: NexusSynthesisEvent.avsc
     */
    public static final String NEXUS_SYNTHESIS = "nexus.synthesis.completed";
    
    /**
     * Reasoning inference events.
     * Schema: NexusReasoningEvent.avsc
     */
    public static final String NEXUS_REASONING = "nexus.reasoning.inferences";
    
    /**
     * Temporal query results.
     * Schema: NexusTemporalEvent.avsc
     */
    public static final String NEXUS_TEMPORAL = "nexus.temporal.queries";
    
    /**
     * Contradiction detection events.
     */
    public static final String NEXUS_CONTRADICTIONS = "nexus.contradictions.detected";
    
    /**
     * Decision execution status updates.
     */
    public static final String NEXUS_DECISIONS = "nexus.decisions.status";
    
    // =========================================
    // PLATO Topics
    // =========================================
    
    /**
     * Governance decision events.
     * Schema: PlatoEvent.avsc
     */
    public static final String PLATO_GOVERNANCE = "plato.governance.decisions";
    
    /**
     * Policy violation events.
     */
    public static final String PLATO_VIOLATIONS = "plato.violations.detected";
    
    /**
     * Approval workflow events.
     */
    public static final String PLATO_APPROVALS = "plato.approvals.events";
    
    /**
     * Spec/Artifact creation events.
     */
    public static final String PLATO_SPECS = "plato.specs.events";
    
    /**
     * Plan execution events.
     */
    public static final String PLATO_PLANS = "plato.plans.execution";
    
    /**
     * Model artifact registration/update events.
     * Published when PERCEPTION models are registered as PLATO artifacts.
     * Schema: PlatoArtifactEvent.avsc
     */
    public static final String PLATO_MODEL_ARTIFACTS = "plato.artifacts.model.events";
    
    /**
     * Feature artifact registration/update events.
     * Published when PERCEPTION features are registered as PLATO artifacts.
     * Schema: PlatoArtifactEvent.avsc
     */
    public static final String PLATO_FEATURE_ARTIFACTS = "plato.artifacts.feature.events";
    
    /**
     * Spec violation events for model/feature quality.
     * Published when performance/bias/quality specs are violated.
     * Schema: SpecViolationEvent.avsc
     */
    public static final String PLATO_SPEC_VIOLATIONS = "plato.specs.violations";
    
    // =========================================
    // SYNAPSE Topics
    // =========================================
    
    /**
     * Action execution events.
     * Schema: SynapseActionRequest.avsc
     */
    public static final String SYNAPSE_ACTIONS = "synapse.actions.executed";
    
    /**
     * Action outcome events.
     * Schema: SynapseOutcomeEvent.avsc
     */
    public static final String SYNAPSE_OUTCOMES = "synapse.actions.outcomes";
    
    /**
     * Execution proof events.
     * Schema: SynapseExecutionProof.avsc
     */
    public static final String SYNAPSE_PROOFS = "synapse.proofs.generated";
    
    /**
     * Safety state changes.
     * Schema: SynapseSafetyStateEvent.avsc
     */
    public static final String SYNAPSE_SAFETY = "synapse.safety.state";
    
    /**
     * Audit events.
     * Schema: SynapseAuditEvent.avsc
     */
    public static final String SYNAPSE_AUDIT = "synapse.audit.events";
    
    // =========================================
    // CORTEX Topics
    // =========================================
    
    /**
     * Agent task request events.
     * Schema: CortexAgentTaskRequest.avsc
     */
    public static final String CORTEX_TASKS = "cortex.agent.tasks";
    
    /**
     * Agent task result events.
     * Schema: CortexAgentResult.avsc
     */
    public static final String CORTEX_RESULTS = "cortex.agent.results";
    
    /**
     * Agent thought streaming events.
     * Schema: CortexAgentThought.avsc
     */
    public static final String CORTEX_THOUGHTS = "cortex.agent.thoughts";
    
    /**
     * Conversation events.
     */
    public static final String CORTEX_CONVERSATIONS = "cortex.conversations";
    
    // =========================================
    // Cross-Service Topics (butterfly.*)
    // =========================================
    
    /**
     * Learning signals for cross-system feedback loops.
     * Schema: LearningSignal.avsc
     */
    public static final String LEARNING_SIGNALS = "butterfly.learning.signals";
    
    /**
     * Learning outcomes for calibration.
     * Schema: LearningOutcome.avsc
     */
    public static final String LEARNING_OUTCOMES = "butterfly.learning.outcomes";
    
    /**
     * Governance violation alerts (cross-service).
     */
    public static final String GOVERNANCE_VIOLATIONS = "butterfly.governance.violations";
    
    /**
     * Governance policy updates.
     * Schema: GovernancePolicy.avsc
     */
    public static final String GOVERNANCE_POLICIES = "butterfly.governance.policies";
    
    /**
     * Ecosystem health status events.
     */
    public static final String ECOSYSTEM_HEALTH = "butterfly.ecosystem.health";
    
    /**
     * Circuit breaker state changes.
     */
    public static final String CIRCUIT_BREAKER_EVENTS = "butterfly.circuit-breaker.events";
    
    /**
     * Cross-system correlation events.
     * Schema: CrossSystemCorrelation.avsc
     */
    public static final String CROSS_CORRELATIONS = "butterfly.correlations";
    
    /**
     * Audit events across all services.
     * Schema: AuditEvent.avsc
     */
    public static final String AUDIT_EVENTS = "butterfly.audit.events";
    
    // =========================================
    // RIM (Reality Integration Mesh) Topics
    // =========================================
    
    /**
     * RIM fast path events for real-time processing.
     * Schema: RimFastEvent.avsc
     */
    public static final String RIM_FAST_PATH = "rim.fastpath.events";
    
    /**
     * RIM state updates.
     */
    public static final String RIM_STATE = "rim.state.updates";
    
    /**
     * RIM node status changes.
     */
    public static final String RIM_NODE_STATUS = "rim.node.status";
    
    // =========================================
    // Identity & Traceability Topics
    // =========================================
    
    /**
     * Event graph updates from NEXUS.
     * Published when event graphs are updated or completed.
     * Schema: EventGraphUpdate.avsc
     */
    public static final String EVENT_GRAPH_UPDATES = "nexus.graph.updates";
    
    /**
     * Decision Episode creation events from CAPSULE.
     * Published when decision episodes are created or completed.
     * Schema: DecisionEpisodeEvent.avsc
     */
    public static final String DECISION_EPISODES = "capsule.episodes.created";
    
    /**
     * Decision Episode event appends.
     * Published when new events are appended to a decision episode.
     */
    public static final String DECISION_EPISODE_EVENTS = "capsule.episodes.events";
    
    /**
     * Connector RIM mapping events from SYNAPSE.
     * Published when external resources are mapped to RIM nodes.
     * Schema: ConnectorRimMapping.avsc
     */
    public static final String CONNECTOR_RIM_MAPPINGS = "synapse.rim.mappings";
    
    /**
     * RIM identity resolution requests.
     * Used for resolving external system identities to RIM nodes.
     */
    public static final String RIM_IDENTITY_RESOLUTION = "butterfly.rim.identity.resolution";
    
    /**
     * Causal chain discovery events.
     * Published when NEXUS discovers new causal chains.
     */
    public static final String CAUSAL_CHAINS = "nexus.causal.chains";
    
    // =========================================
    // Dead Letter Queue Topics
    // =========================================
    
    /**
     * DLQ for PERCEPTION events.
     */
    public static final String DLQ_PERCEPTION = "perception.events.dlq";
    
    /**
     * DLQ for CAPSULE events.
     */
    public static final String DLQ_CAPSULE = "capsule.events.dlq";
    
    /**
     * DLQ for ODYSSEY events.
     */
    public static final String DLQ_ODYSSEY = "odyssey.events.dlq";
    
    /**
     * DLQ for NEXUS events.
     */
    public static final String DLQ_NEXUS = "nexus.events.dlq";
    
    /**
     * DLQ for PLATO events.
     */
    public static final String DLQ_PLATO = "plato.events.dlq";
    
    /**
     * DLQ for SYNAPSE events.
     */
    public static final String DLQ_SYNAPSE = "synapse.events.dlq";
    
    /**
     * DLQ for CORTEX events.
     */
    public static final String DLQ_CORTEX = "cortex.events.dlq";
    
    /**
     * DLQ for RIM events.
     */
    public static final String DLQ_RIM = "rim.dlq";
    
    /**
     * Generic DLQ for cross-service events.
     */
    public static final String DLQ_BUTTERFLY = "butterfly.events.dlq";
    
    // =========================================
    // Utility Methods
    // =========================================
    
    /**
     * Generate DLQ topic name for a given topic.
     * 
     * @param originalTopic The original topic name
     * @return The DLQ topic name
     */
    public static String dlqTopic(String originalTopic) {
        if (originalTopic.endsWith(".dlq")) {
            return originalTopic;
        }
        return originalTopic + ".dlq";
    }
    
    /**
     * Generate retry topic name for a given topic.
     * 
     * @param originalTopic The original topic name
     * @param attempt Retry attempt number
     * @return The retry topic name
     */
    public static String retryTopic(String originalTopic, int attempt) {
        return originalTopic + ".retry." + attempt;
    }
    
    /**
     * Check if a topic is a DLQ topic.
     * 
     * @param topic The topic name to check
     * @return true if the topic is a DLQ
     */
    public static boolean isDlqTopic(String topic) {
        return topic != null && topic.endsWith(".dlq");
    }
    
    /**
     * Get the service name from a topic.
     * 
     * @param topic The topic name
     * @return The service name (first segment)
     */
    public static String getServiceFromTopic(String topic) {
        if (topic == null || topic.isEmpty()) {
            return "unknown";
        }
        int dotIndex = topic.indexOf('.');
        return dotIndex > 0 ? topic.substring(0, dotIndex) : topic;
    }
}
