package com.z254.butterfly.common.api;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

import java.net.URI;
import java.time.Instant;
import java.util.LinkedHashMap;
import java.util.Map;

/**
 * RFC 7807 Problem Details for HTTP APIs.
 * 
 * <p>This class provides a standard format for error responses across all
 * BUTTERFLY ecosystem services. It follows RFC 7807 specification with
 * additional extensions for distributed tracing.
 * 
 * <h2>Standard Fields</h2>
 * <ul>
 *   <li>{@code type} - URI reference identifying the problem type</li>
 *   <li>{@code title} - Short, human-readable summary</li>
 *   <li>{@code status} - HTTP status code</li>
 *   <li>{@code detail} - Human-readable explanation specific to this occurrence</li>
 *   <li>{@code instance} - URI reference identifying the specific occurrence</li>
 * </ul>
 * 
 * <h2>BUTTERFLY Extensions</h2>
 * <ul>
 *   <li>{@code traceId} - Distributed tracing correlation ID</li>
 *   <li>{@code timestamp} - ISO 8601 timestamp of error occurrence</li>
 *   <li>{@code service} - Originating service identifier</li>
 *   <li>{@code errorCode} - Machine-readable error code</li>
 * </ul>
 * 
 * <h2>Usage Example</h2>
 * <pre>{@code
 * ProblemDetail problem = ProblemDetail.builder()
 *     .type(URI.create("https://api.butterfly.254studioz.com/errors/not-found"))
 *     .title("Resource Not Found")
 *     .status(404)
 *     .detail("Capsule with ID 'abc-123' was not found")
 *     .instance(URI.create("/api/v1/capsules/abc-123"))
 *     .traceId("trace-456")
 *     .service("capsule")
 *     .build();
 * }</pre>
 * 
 * @see <a href="https://www.rfc-editor.org/rfc/rfc7807">RFC 7807</a>
 * @since 1.0.0
 */
@JsonInclude(JsonInclude.Include.NON_NULL)
@JsonPropertyOrder({"type", "title", "status", "detail", "instance", "traceId", "timestamp", "service", "errorCode"})
public record ProblemDetail(
        /**
         * A URI reference that identifies the problem type.
         * When dereferenced, it should provide human-readable documentation.
         */
        @JsonProperty("type")
        URI type,
        
        /**
         * A short, human-readable summary of the problem type.
         * Should not change from occurrence to occurrence.
         */
        @JsonProperty("title")
        String title,
        
        /**
         * The HTTP status code generated by the origin server.
         */
        @JsonProperty("status")
        int status,
        
        /**
         * A human-readable explanation specific to this occurrence.
         */
        @JsonProperty("detail")
        String detail,
        
        /**
         * A URI reference that identifies the specific occurrence of the problem.
         */
        @JsonProperty("instance")
        URI instance,
        
        /**
         * BUTTERFLY extension: distributed tracing correlation ID.
         */
        @JsonProperty("traceId")
        String traceId,
        
        /**
         * BUTTERFLY extension: ISO 8601 timestamp of error occurrence.
         */
        @JsonProperty("timestamp")
        Instant timestamp,
        
        /**
         * BUTTERFLY extension: originating service identifier.
         */
        @JsonProperty("service")
        String service,
        
        /**
         * BUTTERFLY extension: machine-readable error code for client handling.
         */
        @JsonProperty("errorCode")
        String errorCode,
        
        /**
         * Additional extension properties.
         */
        @JsonProperty("extensions")
        Map<String, Object> extensions
) {
    
    /**
     * Common error types as URIs.
     */
    public static final class ErrorTypes {
        private static final String BASE_URI = "https://api.butterfly.254studioz.com/errors";
        
        public static final URI NOT_FOUND = URI.create(BASE_URI + "/not-found");
        public static final URI BAD_REQUEST = URI.create(BASE_URI + "/bad-request");
        public static final URI VALIDATION_ERROR = URI.create(BASE_URI + "/validation-error");
        public static final URI UNAUTHORIZED = URI.create(BASE_URI + "/unauthorized");
        public static final URI FORBIDDEN = URI.create(BASE_URI + "/forbidden");
        public static final URI CONFLICT = URI.create(BASE_URI + "/conflict");
        public static final URI RATE_LIMITED = URI.create(BASE_URI + "/rate-limited");
        public static final URI SERVICE_UNAVAILABLE = URI.create(BASE_URI + "/service-unavailable");
        public static final URI INTERNAL_ERROR = URI.create(BASE_URI + "/internal-error");
        public static final URI GATEWAY_ERROR = URI.create(BASE_URI + "/gateway-error");
        public static final URI CIRCUIT_OPEN = URI.create(BASE_URI + "/circuit-open");
        public static final URI TIMEOUT = URI.create(BASE_URI + "/timeout");
        public static final URI GOVERNANCE_VIOLATION = URI.create(BASE_URI + "/governance-violation");
        public static final URI POLICY_DENIED = URI.create(BASE_URI + "/policy-denied");
        public static final URI TENANT_NOT_FOUND = URI.create(BASE_URI + "/tenant-not-found");
        public static final URI UNSUPPORTED_VERSION = URI.create(BASE_URI + "/unsupported-version");
        
        private ErrorTypes() {}
    }
    
    /**
     * Create a builder for ProblemDetail.
     */
    public static Builder builder() {
        return new Builder();
    }
    
    /**
     * Create a simple 404 Not Found response.
     */
    public static ProblemDetail notFound(String detail, String traceId) {
        return builder()
                .type(ErrorTypes.NOT_FOUND)
                .title("Not Found")
                .status(404)
                .detail(detail)
                .traceId(traceId)
                .build();
    }
    
    /**
     * Create a simple 400 Bad Request response.
     */
    public static ProblemDetail badRequest(String detail, String traceId) {
        return builder()
                .type(ErrorTypes.BAD_REQUEST)
                .title("Bad Request")
                .status(400)
                .detail(detail)
                .traceId(traceId)
                .build();
    }
    
    /**
     * Create a validation error response.
     */
    public static ProblemDetail validationError(String detail, String traceId, Map<String, Object> fieldErrors) {
        return builder()
                .type(ErrorTypes.VALIDATION_ERROR)
                .title("Validation Error")
                .status(400)
                .detail(detail)
                .traceId(traceId)
                .extension("fieldErrors", fieldErrors)
                .build();
    }
    
    /**
     * Create a 401 Unauthorized response.
     */
    public static ProblemDetail unauthorized(String detail, String traceId) {
        return builder()
                .type(ErrorTypes.UNAUTHORIZED)
                .title("Unauthorized")
                .status(401)
                .detail(detail)
                .traceId(traceId)
                .build();
    }
    
    /**
     * Create a 403 Forbidden response.
     */
    public static ProblemDetail forbidden(String detail, String traceId) {
        return builder()
                .type(ErrorTypes.FORBIDDEN)
                .title("Forbidden")
                .status(403)
                .detail(detail)
                .traceId(traceId)
                .build();
    }
    
    /**
     * Create a 429 Rate Limited response.
     */
    public static ProblemDetail rateLimited(String detail, String traceId, long retryAfterSeconds) {
        return builder()
                .type(ErrorTypes.RATE_LIMITED)
                .title("Rate Limited")
                .status(429)
                .detail(detail)
                .traceId(traceId)
                .extension("retryAfter", retryAfterSeconds)
                .build();
    }
    
    /**
     * Create a 503 Service Unavailable response.
     */
    public static ProblemDetail serviceUnavailable(String detail, String traceId, String downstreamService) {
        return builder()
                .type(ErrorTypes.SERVICE_UNAVAILABLE)
                .title("Service Unavailable")
                .status(503)
                .detail(detail)
                .traceId(traceId)
                .extension("downstreamService", downstreamService)
                .build();
    }
    
    /**
     * Create a 500 Internal Error response.
     */
    public static ProblemDetail internalError(String detail, String traceId) {
        return builder()
                .type(ErrorTypes.INTERNAL_ERROR)
                .title("Internal Server Error")
                .status(500)
                .detail(detail)
                .traceId(traceId)
                .build();
    }
    
    /**
     * Create a circuit breaker open response.
     */
    public static ProblemDetail circuitOpen(String detail, String traceId, String circuitName) {
        return builder()
                .type(ErrorTypes.CIRCUIT_OPEN)
                .title("Service Circuit Open")
                .status(503)
                .detail(detail)
                .traceId(traceId)
                .extension("circuit", circuitName)
                .build();
    }
    
    /**
     * Builder for ProblemDetail.
     */
    public static class Builder {
        private URI type = ErrorTypes.INTERNAL_ERROR;
        private String title;
        private int status = 500;
        private String detail;
        private URI instance;
        private String traceId;
        private Instant timestamp = Instant.now();
        private String service;
        private String errorCode;
        private Map<String, Object> extensions;
        
        public Builder type(URI type) {
            this.type = type;
            return this;
        }
        
        public Builder title(String title) {
            this.title = title;
            return this;
        }
        
        public Builder status(int status) {
            this.status = status;
            return this;
        }
        
        public Builder detail(String detail) {
            this.detail = detail;
            return this;
        }
        
        public Builder instance(URI instance) {
            this.instance = instance;
            return this;
        }
        
        public Builder instance(String path) {
            this.instance = URI.create(path);
            return this;
        }
        
        public Builder traceId(String traceId) {
            this.traceId = traceId;
            return this;
        }
        
        public Builder timestamp(Instant timestamp) {
            this.timestamp = timestamp;
            return this;
        }
        
        public Builder service(String service) {
            this.service = service;
            return this;
        }
        
        public Builder errorCode(String errorCode) {
            this.errorCode = errorCode;
            return this;
        }
        
        public Builder extensions(Map<String, Object> extensions) {
            this.extensions = extensions;
            return this;
        }
        
        public Builder extension(String key, Object value) {
            if (this.extensions == null) {
                this.extensions = new LinkedHashMap<>();
            }
            this.extensions.put(key, value);
            return this;
        }
        
        public ProblemDetail build() {
            return new ProblemDetail(
                    type, title, status, detail, instance,
                    traceId, timestamp, service, errorCode, extensions
            );
        }
    }
}
